create table quran_pack
(
    id bigint auto_increment
        primary key
);

INSERT INTO quran.quran_pack (id) VALUES (1);
INSERT INTO quran.quran_pack (id) VALUES (2);
INSERT INTO quran.quran_pack (id) VALUES (3);
INSERT INTO quran.quran_pack (id) VALUES (4);
INSERT INTO quran.quran_pack (id) VALUES (5);
INSERT INTO quran.quran_pack (id) VALUES (6);
INSERT INTO quran.quran_pack (id) VALUES (7);
INSERT INTO quran.quran_pack (id) VALUES (8);
INSERT INTO quran.quran_pack (id) VALUES (9);
INSERT INTO quran.quran_pack (id) VALUES (10);
INSERT INTO quran.quran_pack (id) VALUES (11);
INSERT INTO quran.quran_pack (id) VALUES (12);
INSERT INTO quran.quran_pack (id) VALUES (13);
INSERT INTO quran.quran_pack (id) VALUES (14);
INSERT INTO quran.quran_pack (id) VALUES (15);
INSERT INTO quran.quran_pack (id) VALUES (16);
INSERT INTO quran.quran_pack (id) VALUES (17);
INSERT INTO quran.quran_pack (id) VALUES (18);
INSERT INTO quran.quran_pack (id) VALUES (19);
INSERT INTO quran.quran_pack (id) VALUES (20);
INSERT INTO quran.quran_pack (id) VALUES (21);
INSERT INTO quran.quran_pack (id) VALUES (22);
INSERT INTO quran.quran_pack (id) VALUES (23);
INSERT INTO quran.quran_pack (id) VALUES (24);
INSERT INTO quran.quran_pack (id) VALUES (25);
INSERT INTO quran.quran_pack (id) VALUES (26);
INSERT INTO quran.quran_pack (id) VALUES (27);
INSERT INTO quran.quran_pack (id) VALUES (28);
INSERT INTO quran.quran_pack (id) VALUES (29);
INSERT INTO quran.quran_pack (id) VALUES (30);
INSERT INTO quran.quran_pack (id) VALUES (31);
INSERT INTO quran.quran_pack (id) VALUES (32);
INSERT INTO quran.quran_pack (id) VALUES (33);
INSERT INTO quran.quran_pack (id) VALUES (34);
INSERT INTO quran.quran_pack (id) VALUES (35);
INSERT INTO quran.quran_pack (id) VALUES (36);
INSERT INTO quran.quran_pack (id) VALUES (37);
INSERT INTO quran.quran_pack (id) VALUES (38);
INSERT INTO quran.quran_pack (id) VALUES (39);
INSERT INTO quran.quran_pack (id) VALUES (40);
INSERT INTO quran.quran_pack (id) VALUES (41);
INSERT INTO quran.quran_pack (id) VALUES (42);
INSERT INTO quran.quran_pack (id) VALUES (43);
INSERT INTO quran.quran_pack (id) VALUES (44);
INSERT INTO quran.quran_pack (id) VALUES (45);
INSERT INTO quran.quran_pack (id) VALUES (46);
INSERT INTO quran.quran_pack (id) VALUES (47);
INSERT INTO quran.quran_pack (id) VALUES (48);
INSERT INTO quran.quran_pack (id) VALUES (49);
INSERT INTO quran.quran_pack (id) VALUES (50);
INSERT INTO quran.quran_pack (id) VALUES (51);
INSERT INTO quran.quran_pack (id) VALUES (52);
INSERT INTO quran.quran_pack (id) VALUES (53);
INSERT INTO quran.quran_pack (id) VALUES (54);
INSERT INTO quran.quran_pack (id) VALUES (55);
INSERT INTO quran.quran_pack (id) VALUES (56);
INSERT INTO quran.quran_pack (id) VALUES (57);
INSERT INTO quran.quran_pack (id) VALUES (58);
INSERT INTO quran.quran_pack (id) VALUES (59);
INSERT INTO quran.quran_pack (id) VALUES (60);
INSERT INTO quran.quran_pack (id) VALUES (61);
