# Generated by Django 4.1.6 on 2023-02-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('sura', models.IntegerField()),
                ('aya', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
