# Generated by Django 4.1.6 on 2023-02-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuranText',
            fields=[
                ('ayah_id', models.AutoField(primary_key=True, serialize=False)),
                ('surah_id', models.IntegerField()),
                ('ayah', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
