# Generated by Django 4.1.6 on 2023-02-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qurantext',
            options={'managed': False},
        ),
    ]
