# Generated by Django 4.1.6 on 2023-02-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='sura_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
