# Generated by Django 4.1.6 on 2023-02-13 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_alter_qurantext_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qurantext',
            table='quran_text',
        ),
    ]
