# Generated by Django 4.1.6 on 2023-02-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0003_alter_qurantext_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('sura', models.IntegerField()),
                ('aya', models.IntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'quran_text',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='QuranText',
        ),
    ]
