# Generated by Django 4.1.6 on 2023-02-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0004_text_delete_qurantext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={},
        ),
    ]
