# Generated by Django 4.1.6 on 2023-02-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0005_alter_text_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='page_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='text',
            table=None,
        ),
    ]
