# Generated by Django 4.1.6 on 2023-02-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0006_text_page_start_alter_text_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='sura_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
