# Generated by Django 4.1.6 on 2023-02-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0007_text_sura_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='page_start',
        ),
    ]
